site_name: PSFabrik
default: Iker Landajuela
theme: readthedocs
repo_url: https://github.com/ikerlandajuela/PowerShell/
pages:
    - Inicio: index.md
    - Sintaxis:
        - 'Bucles': 'sintaxis/bucles.md'
    - Active Directory:
        - 'Instalación del modulo':  'active-directory/instalar-modulo.md'
    - Recursos: recursos.md
