site_name: PSFabrik
default: Iker Landajuela
theme: readthedocs
repo_url: https://github.com/ikerlandajuela/PowerShell/
pages:
    - Inicio: index.md
    - General:
        - 'Instalación': 'general/instalacion.md'
    - Sintaxis:
        - 'Variables': 'sintaxis/variables.md'
        - 'Objetos': 'sintaxis/objetos.md'
        - 'If': 'sintaxis/if.md'
        - 'Arrays': 'sintaxis/array.md'
        - 'For': 'sintaxis/for.md'
        - 'Foreach': 'sintaxis/foreach.md'
        - 'Function': 'sintaxis/function.md'
        - 'While': 'sintaxis/while.md'
        - 'Select': 'sintaxis/select.md'
        - 'Switch': 'sintaxis/switch.md'
        - 'Pipe': 'sintaxis/pipe.md'
    - Sistema:
        - 'Directorios': 'sistema-archivos/directorios.md'
    - Admin:
        - 'Event Logs': 'admin/event-log/event-log.md'
    - Networking:
        - 'Sesiones remotas' : 'networking/remoto.md'
        - 'cURL': 'networking/curl.md'
        - 'RESTful APIs': 'networking/restful_apis.md'
    - Active Directory:
        - 'Cuentas usuarios':  'active-directory/cuentas-usuarios.md'
        - 'Grupos': 'active-directory/grupos.md'
    - Exchange Server:
         - 'Básico': 'exchange/basico.md'
    - Bases de datos:
        - 'SQLite': 'bases_de_datos/sqlite/sqlite.md'
    - Recursos: recursos.md
