site_name: PSFabrik
default: Iker Landajuela
theme: readthedocs
repo_url: https://github.com/ikerlandajuela/PowerShell/
pages:
    - Inicio: index.md
    - Sintaxis:
        - 'Arrays': 'sintaxis/array.md'   
        - 'For': 'sintaxis/for.md'
        - 'Foreach': 'sintaxis/foreach.md'
    - Active Directory:
        - 'Instalación del modulo':  'active-directory/instalar-modulo.md'
    - Recursos: recursos.md
