site_name: PSFabrik
default: Iker Landajuela
theme: readthedocs
repo_url: https://github.com/ikerlandajuela/PowerShell/
pages:
    - Inicio: index.md
    - Sintaxis:
        - 'Arrays': 'sintaxis/array.md'   
        - 'For': 'sintaxis/for.md'
        - 'Foreach': 'sintaxis/foreach.md'
        - 'Function': 'sintaxis/function.md'
    - Sistema archivos:
        - 'Directorios': 'sistema-archivos/directorios.md'
    - Bases de datos:
        - 'SQLite': 'bases_de_datos/sqlite/sqlite.md'
    - Admin:
        - 'Event Logs': 'admin/event-log.md'
    - Active Directory:
        - 'Cuentas usuarios':  'active-directory/cuentas-usuarios.md'
        - 'Grupos': 'active-directory/grupos.md'
    - Recursos: recursos.md
